apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-neuron-cache
  labels:
    app: vllm-neuron
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 50Gi
